### PR TITLE
Added a Quick Add Script and Keyword

### PR DESCRIPTION
**Pull request by tarasivashchuk**
- Added a script which uses a given argument to create a task in your Inbox.
- Uses the “add” keyword by default.
- Requires an argument, which is the title of the task.
- Optionally takes arguments prepended with a “#” which will be added with tags.
- All credit goes to Cultured Code for this script, all I did was add it to this workflow.

Signed-off-by: Taras Ivashchuk <taras@tarasivashchuk.com>

### CODE REVIEW

**Comment by tarasivashchuk** [comment]
Literally just took the Things workflow offered directly by Cultured Code and added it to this workflow. It is a bare-bones quick add script which allows you to quickly add a task to your inbox with the “+” keyword, which I changed to “add”.

I have it set up this way and figured others would probably find it useful as well, as your workflow is awesome, but having a quick keyword to just create a quick task is useful as well.

**Comment by xilopaint** [comment]
Hi @tarasivashchuk! How can this be any better than the built-in quick entry panel?

**Comment by tarasivashchuk** [comment]
@xilopaint it’s probably not, I didn’t know there was a quick entry panel at the time, sorry - feel free to disregard this pull request 😅

**Comment by xilopaint** [comment]
No problem!

**Pull request closed without merging**
